[project]
name = "pydanticai-experiment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai>=1.0.10",
    "pytest>=8.4.2",
]

[tool.pytest.ini_options]
addopts = "-s"
